### ISSUE TITLE
Establish GBIF data call for taxonomy selection and pulling occurrance data

### ISSUE THREAD

**Issue by dcarver1** [AtlantaBotanicalGarden/gap-analysis-shiny-app#1]
Primary need. 
Use a selected taxonomy to populate a gbif api call to get occurrence data into the application 

guidelines 
- use rgbif over web native api calls when possible 
- Focus on a core set of genera (5 oak, magnolia, vitis, two of your choosing ) due to the tight development time line on the first training 
- keep some notes or expectations on how to handle the scaling to full taxanomic search. 

Just note from progress updates on this issue as they feel relevant.

**Comment by dcarver1** [comment]
It's unlikely that the application will be able to use API calls for populating the species selection drop downs. This is mostly due to the limited functionality in handling the  "infraspecific epithets"

The work around for the moment is to use a file containing all gensus, species, and GBIF unique ids. This is about ~160mb that needs to be loaded with each application instance. 

Might be to find way to lighten this

**Comment by dcarver1** [comment]
@Jonathan-Gore 
The main branch has a few edits to the gather and prep gbif functions. Feel free to check these out. 

This is gather and displaying the pulled data on the map/table. Everything is rough, specifically the clearing of species information, but its a reasonable start.

**Comment by Jonathan-Gore** [comment]
@dcarver1 Updated the GBIF Species API calls in a new branch "GBIF-Species-API-calls". Currently is in a drafted form, but was successfully querying GBIF for taxa information. Will need to continue testing, integrating into the current dropdowns may require using something like debounce or throttle from the shiny package to try and slow down API calls incase a user is correcting spelling.
