### ISSUE TITLE
GBIF query

### ISSUE THREAD

**Issue by dcarver1** [AtlantaBotanicalGarden/gap-analysis-shiny-app#6]
So there appears to be multiple sets of unique column names for species... 

See Vitis acerfolia : 5372375  species. for one that works. 

Vitis arizonica : 5372421 species, for one that does not work 

We need to some conditional work in handling this varability within the `etl_gbif_occ_data` function. 

Though I have to admit it is strange to see this different in column names coming from the same source?

**Comment by dcarver1** [comment]
@Jonathan-Gore 
If you have time to take a look at this behavior let me know. most why is there is a difference schema between difference species calls? Hoping I'm just messing something up on my end.

**Comment by Jonathan-Gore** [comment]
We'll talk later tomorrow/this week when you get the chance. I looks like Vitis arizonica has no occurrences in GBIF. I may not being fully understanding the issue, but yes definitely `etl_gbif_occ_data` likely needs many aspects of validations integrated.

**Comment by Jonathan-Gore** [comment]
@dcarver1 I believe my current PR for the "gbif-backbone-select-fix" branch closes this issue. Feel free to close after testing/merging.

**Comment by dcarver1** [comment]
The gbif query is working really well
